include:
  # Node.js template
  - component: "$CI_SERVER_FQDN/to-be-continuous/node/gitlab-ci-node@5"
    inputs:
      publish-enabled: true
  # Docker template
  - component: "$CI_SERVER_FQDN/to-be-continuous/docker/gitlab-ci-docker@8"
  # Semantic-release template
  - component: "$CI_SERVER_FQDN/to-be-continuous/semantic-release/gitlab-ci-semrel@4"
