include:
  # Node.js template
  - component: "$CI_SERVER_FQDN/to-be-continuous/node/gitlab-ci-node@4.2.6"
    inputs:
      publish-enabled: true
  # Docker template
  - component: "$CI_SERVER_FQDN/to-be-continuous/docker/gitlab-ci-docker@6.2.2"
  # Semantic-release template
  - component: "$CI_SERVER_FQDN/to-be-continuous/semantic-release/gitlab-ci-semrel@3.14.4"
